#!/usr/bin/env bash
# This script configure SSH configuration file to our needs

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
